services:
  wordpress:
    image: wordpress:6.8.0-php8.2
    #image: wordpress:6.7-php8.1
    depends_on:
      - db
    restart: always
    ports:
      - "${WP_HTTP_PORT}:80"
      - "${WP_HTTPS_PORT}:443"
    environment:
      DOMAIN: ${DOMAIN}
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
      - ./wp-content/themes:/var/www/html/wp-content/themes/
      - ./wp-content/uploads:/var/www/html/wp-content/uploads
      - ./wp-content/post-install.sh:/var/www/html/wp-content/post-install.sh
    post_start:
      - command: ["sh", "-c", "/var/www/html/wp-content/post-install.sh"]


      # - ./data:/var/www/html
      
      - /etc/letsencrypt/live/portainer-eu.matrix-test.com/fullchain.pem:/etc/ssl/certs/portainer.crt
      - /etc/letsencrypt/live/portainer-eu.matrix-test.com/privkey.pem:/etc/ssl/private/portainer.key
    command: >
      bash -c "apt-get update && 
      a2enmod ssl && 
      curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && chmod +x wp-cli.phar && 
      mv wp-cli.phar /usr/local/bin/wp &&
      echo '<VirtualHost *:443>
          ServerName your-domain.com
          DocumentRoot /var/www/html
          SSLEngine on
          SSLCertificateFile /etc/ssl/certs/portainer.crt
          SSLCertificateKeyFile /etc/ssl/private/portainer.key
          <Directory /var/www/html>
              AllowOverride All
              Require all granted
          </Directory>
      </VirtualHost>' > /etc/apache2/sites-available/default-ssl.conf &&
      a2ensite default-ssl &&
      docker-entrypoint.sh apache2-foreground"

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db

volumes:
  data:
  db:

