services:
  wordpress:
    image: ${WORDPRESS_IMAGE}
    depends_on:
      - db
    restart: always
    ports:
      - "${WP_HTTP_PORT}:80"
      - "${WP_HTTPS_PORT}:443"
    environment:
      DOMAIN: ${DOMAIN}
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
      - ./wp-content/themes:/var/www/html/wp-content/themes/
      - ./wp-content/uploads:/var/www/html/wp-content/uploads
      - ./wp-content/post-install.sh:/var/www/html/wp-content/post-install.sh
      - ./.env:/var/www/html/.env
      - ./php.ini-prod:/usr/local/etc/php/php.ini
      - /etc/letsencrypt/live/portainer-eu.matrix-test.com/fullchain.pem:/etc/ssl/certs/portainer.crt
      - /etc/letsencrypt/live/portainer-eu.matrix-test.com/privkey.pem:/etc/ssl/private/portainer.key

      # - ./data:/var/www/html
    command: >
      bash -c "apt-get update && 
      a2enmod ssl &&
      echo '<VirtualHost *:443>
          ServerName your-domain.com
          DocumentRoot /var/www/html
          SSLEngine on
          SSLCertificateFile /etc/ssl/certs/portainer.crt
          SSLCertificateKeyFile /etc/ssl/private/portainer.key
          <Directory /var/www/html>
              AllowOverride All
              Require all granted
          </Directory>
      </VirtualHost>' > /etc/apache2/sites-available/default-ssl.conf &&
      a2ensite default-ssl &&
      docker-entrypoint.sh apache2-foreground"

  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db

volumes:
  data:
  db:

